package com.pvv.pulbet.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.pvv.pulbet.dao.ApuestaDAO;
import com.pvv.pulbet.dao.LineaApuestaDAO;
import com.pvv.pulbet.dao.util.ConnectionManager;
import com.pvv.pulbet.dao.util.JDBCUtils;
import com.pvv.pulbet.exceptions.DataException;
import com.pvv.pulbet.exceptions.DuplicateInstanceException;
import com.pvv.pulbet.exceptions.InstanceNotFoundException;
import com.pvv.pulbet.model.Apuesta;
import com.pvv.pulbet.model.LineaApuesta;

public class ApuestaDAOImpl implements ApuestaDAO{

	LineaApuestaDAO lineaApuestaDAO= null;
	
	public ApuestaDAOImpl() {
		lineaApuestaDAO = new LineaApuestaDAOImpl();
	}

	@Override
	public Apuesta findById(Connection connection, Integer id)
			throws InstanceNotFoundException, DataException {
		Apuesta a = null;

		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			connection = ConnectionManager.getConnection();

			String sql;
			sql =  "SELECT ID_APUESTA, IMPORTE, ID_USUARIO, FECHA "
					+"FROM APUESTA "
					+"WHERE ID_USUARIO = ? ";

			// Preparar a query
			System.out.println("Creating statement...");
			preparedStatement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

			// Establece os parámetros
			int i = 1;
			preparedStatement.setLong(i++, id);


			resultSet = preparedStatement.executeQuery();			
			//STEP 5: Extract data from result set			

			if (resultSet.next()) {
				a =  loadNext(resultSet);			
				//System.out.println("Cargado "+u);
			} else {
				throw new InstanceNotFoundException("Non se atopou apuesta con id = "+id, Apuesta.class.getName());
			}


		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {            
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);
		}  	

		return a;
	}

	@Override
	public List<Apuesta> findByUsuario(Connection connection, Integer id)
			throws DataException {


		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			connection = ConnectionManager.getConnection();

			String sql;
			sql =  "SELECT ID_APUESTA, IMPORTE, ID_USUARIO, FECHA "
					+"FROM APUESTA "
					+"WHERE ID_USUARIO = ? ";

			// Preparar a query
			System.out.println("Creating statement...");
			preparedStatement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

			// Establece os parámetros
			int i = 1;
			preparedStatement.setLong(i++, id);


			resultSet = preparedStatement.executeQuery();			
			//STEP 5: Extract data from result set			

			List<Apuesta> results = new ArrayList<Apuesta>();                        
			Apuesta a = null;


			while(resultSet.next()) {
				a = loadNext(resultSet);
				results.add(a);               	
			}

			return results;

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {            
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);
		}  	

	}

	//falta algun finder para buscar apostas deperminadas, inda non determinadas e eso...

	@Override
	public Apuesta create(Connection connection, Apuesta a) 
			throws DuplicateInstanceException, DataException{
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {          

			connection = ConnectionManager.getConnection();


			String queryString = "INSERT INTO APUESTA(IMPORTE, ID_USUARIO, FECHA) "
					+ "VALUES (?, ?, ?)";

			preparedStatement = connection.prepareStatement(queryString, Statement.RETURN_GENERATED_KEYS);

			int i = 1;     			
			preparedStatement.setDouble(i++, a.getImporte());
			preparedStatement.setLong(i++, a.getIdUsuario());
			preparedStatement.setDate(i++, new java.sql.Date(a.getFecha().getTime()));



			int insertedRows = preparedStatement.executeUpdate();

			if (insertedRows == 0) {
				throw new SQLException("Can not add row to table 'Apuesta'");
			}

			resultSet = preparedStatement.getGeneratedKeys();
			if (resultSet.next()) {
				Long id = resultSet.getLong(1);
				a.setIdApuesta(id);				
			} else {
				throw new DataException("Unable to fetch autogenerated primary key");
			}

			List<LineaApuesta> lineas = a.getLineas();
			for (LineaApuesta la: lineas) {
				la.setIdApuesta(a.getIdApuesta());
				lineaApuestaDAO.create(connection, la);
			}
			//...
			return a;					

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);			
		}

	}
	
	@Override
	public void update(Connection connection, Apuesta a) throws InstanceNotFoundException, DataException {
		PreparedStatement preparedStatement = null;
		try {
			
			deleteLineasApuesta(connection, a.getIdApuesta());
			
			String queryString = 
					"UPDATE APUESTA " +
					"SET IMPORTE = ? , ID_USUARIO = ? , FECHA = ? " +
					"WHERE ID_APUESTA = ? ";

			preparedStatement = connection.prepareStatement(queryString);

			int i = 1;
			preparedStatement.setDouble(i++, a.getImporte());
			preparedStatement.setLong(i++, a.getIdUsuario());
			preparedStatement.setDate(i++, new java.sql.Date(a.getFecha().getTime()));
			
			

			int updatedRows = preparedStatement.executeUpdate();

			if (updatedRows == 0) {
				throw new InstanceNotFoundException("Non se atopou aposta: "+a.getIdApuesta(), Apuesta.class.getName());
			}

			if (updatedRows > 1) {
				throw new SQLException("Duplicate row for id = '" + 
						a.getIdApuesta() + "' in table 'Apuesta'");
			}     
			
			createLineasPedido(connection, a.getIdApuesta(), a.getLineas());

		} catch (SQLException e) {
			throw new DataException(e);    
		} finally {
			JDBCUtils.closeStatement(preparedStatement);
		}
		
	}
	
	@Override
	public long delete(Connection connection, Long id) 
			throws InstanceNotFoundException, DataException {
		PreparedStatement preparedStatement = null;

		try {
			
			deleteLineasApuesta (connection, id);

			String queryString =	
					  "DELETE FROM APUESTA " 
					+ "WHERE ID_APUESTA = ? ";
			
			preparedStatement = connection.prepareStatement(queryString);

			int i = 1;
			preparedStatement.setLong(i++, id);

			int removedRows = preparedStatement.executeUpdate();

			if (removedRows == 0) {
				throw new InstanceNotFoundException("Non se atopou aposta :"+id, Apuesta.class.getName());
			} 
			return removedRows;

		} catch (SQLException e) {
			throw new DataException(e);
		} finally {
			JDBCUtils.closeStatement(preparedStatement);
		}

	}

	@Override
	public List<Apuesta> findAll(Connection connection) throws DataException {

		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			connection = ConnectionManager.getConnection();

			String sql;
			sql =  "SELECT ID_APUESTA, IMPORTE, ID_USUARIO, FECHA "
					+"FROM APUESTA";

			// Preparar a query
			System.out.println("Creating statement...");
			preparedStatement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

			resultSet = preparedStatement.executeQuery();			
			//STEP 5: Extract data from result set			

			List<Apuesta> results = new ArrayList<Apuesta>();                        
			Apuesta a = null;


			while(resultSet.next()) {
				a = loadNext(resultSet);
				results.add(a);               	
			}

			return results;

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {            
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);
		}  	
	}



	private Apuesta loadNext(ResultSet resultSet) 
			throws SQLException{


		Apuesta a = new Apuesta();
		int i = 1;
		Long idApuesta = resultSet.getLong(i++);
		Double importe = resultSet.getDouble(i++);
		Long idUsuario = resultSet.getLong(i++); 
		Date fecha = resultSet.getDate(i++);

		a.setIdApuesta(idApuesta);
		a.setImporte(importe);
		a.setFecha(fecha);
		a.setIdUsuario(idUsuario);
		//Departamento d = departamentoDAO.findByIdEmpleado() temos que crear private departamentoDAO = new departamentoDAO() en departamentoDAO
		// u.setDeptId

		return a;

	}
	
	protected void deleteLineasApuesta(Connection c, Long idApuesta)
			throws SQLException, DataException {

			PreparedStatement preparedStatement = null;

			try {

				String queryString =	
						  "DELETE FROM LINEA_APUESTA " 
						+ "WHERE ID_APUESTA = ? ";
				
				preparedStatement = c.prepareStatement(queryString);

				int i = 1;
				preparedStatement.setLong(i++,idApuesta);

				preparedStatement.executeUpdate();

			} catch (SQLException e) {
				throw new DataException(e);
			} finally {
				JDBCUtils.closeStatement(preparedStatement);
			}
		}
	
	protected void createLineasPedido(Connection connection, Long idApuesta,  List<LineaApuesta> lineas)
			throws SQLException, DataException {

		PreparedStatement preparedStatement = null;
		try {          
			String queryString = null;
			int i;
			for (LineaApuesta la: lineas ) {
				queryString = "INSERT INTO LINEA_APUESTA (NUMERO_LINEA, ID_APUESTA, ID_RESULTADO, ID_EVENTO) VALUES (?, ?, ?, ?)";
				preparedStatement = connection.prepareStatement(queryString);				

				i = 1;     
				preparedStatement.setLong(i++, la.getNumLinea());
				preparedStatement.setLong(i++, la.getIdApuesta());
				preparedStatement.setLong(i++, la.getIdResultado());
				preparedStatement.setLong(i++, la.getIdEvento());

				int insertedRows = preparedStatement.executeUpdate();

				if (insertedRows == 0) {
					throw new SQLException("Can not add row to table 'LineaApuesta'");
				}	

				JDBCUtils.closeStatement(preparedStatement);
			} 
		} catch (SQLException e) {
			throw new DataException(e);
		} finally {
			JDBCUtils.closeStatement(preparedStatement);
		}
	}




}
