package com.pvv.pulbet.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.pvv.pulbet.dao.ResultadoDAO;
import com.pvv.pulbet.dao.util.ConnectionManager;
import com.pvv.pulbet.dao.util.JDBCUtils;
import com.pvv.pulbet.exception.DataException;
import com.pvv.pulbet.model.Resultado;
import com.pvv.pulbet.model.TipoResultado;

public class ResultadoDAOImpl implements ResultadoDAO{

	@Override
	public Resultado create(Connection connection, Resultado r) throws Exception {
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {          

			connection = ConnectionManager.getConnection();

			String queryString = "INSERT INTO RESULTADO(NOMBRE, ID_TIPO_RESULTADO) "
					+ "VALUES (?,?)";

			preparedStatement = connection.prepareStatement(queryString, Statement.RETURN_GENERATED_KEYS);

			int i = 1;     			
			preparedStatement.setString(i++, r.getNombre());
			preparedStatement.setLong(i++, r.getIdTipoResulatado());

			

			int insertedRows = preparedStatement.executeUpdate();

			if (insertedRows == 0) {
				throw new SQLException("Can not add row to table 'Resultado'");
			}

			resultSet = preparedStatement.getGeneratedKeys();
			if (resultSet.next()) {
				Long id = resultSet.getLong(1);
				r.setIdResultado(id);
			} else {
				throw new DataException("Unable to fetch autogenerated primary key");
			}

			return r;					

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);			
		}

	}

	@Override
	public Long delete(Connection connection, Long id) throws Exception {
		PreparedStatement preparedStatement = null;

		try {
			connection = ConnectionManager.getConnection();

			String queryString =	
					"DELETE FROM RESULTADO " 
					+ "WHERE ID_RESULTADO = ? ";


			preparedStatement = connection.prepareStatement(queryString);

			int i = 1;
			preparedStatement.setLong(i++, id);

			long removedRows = preparedStatement.executeUpdate();


			return removedRows;

		} catch (SQLException e) {
			throw new DataException(e);
		} finally {
			JDBCUtils.closeStatement(preparedStatement);
		}

		
	}
	

	@Override
	public Resultado findById(Connection connection, Integer id) throws Exception {
		Resultado r = null;

		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			connection = ConnectionManager.getConnection();

				
			String sql;
			sql =  "SELECT ID_RESULTADO, NOMBRE, ID_TIPO_RESULTADO "
					+"FROM RESULTADO "
					+"WHERE ID_RESULTADO = ? ";

			// Preparar a query
			System.out.println("Creating statement...");
			preparedStatement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

			// Establece os parámetros
			int i = 1;
			preparedStatement.setLong(i++, id);


			resultSet = preparedStatement.executeQuery();			
			//STEP 5: Extract data from result set			

			if (resultSet.next()) {
				r =  loadNext(resultSet);			
				//System.out.println("Cargado "+u);
			} else {
				throw new Exception("Non se atopou RESULTADO con id = "+id);
			}
			if (resultSet.next()) {
				throw new Exception("RESULTADO con id = "+id+" duplicado");
			}

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {            
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);
		}  	

		return r;
	}

	@Override
	public List<Resultado> findByTipoResultado(Connection connection, Integer id) throws Exception {
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try{

			connection = ConnectionManager.getConnection();

			String sql;
			sql =    "SELECT ID_RESULTADO, NOMBRE, ID_TIPO_RESULTADO " 
					+" FROM RESULTADO "
					+" WHERE "
					+"	ID_RESULTADO = ?";


			// Preparar a query
			System.out.println("Creating statement...");
			preparedStatement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

			// Establece os parámetros
			int i = 1;
			preparedStatement.setLong(i++, id);

			resultSet = preparedStatement.executeQuery();			
			//STEP 5: Extract data from result set			

			List<Resultado> results = new ArrayList<Resultado>();                        
			Resultado r = null;


			while(resultSet.next()) {
				r = loadNext(resultSet);
				results.add(r);               	
			}

			return results;

		} catch (SQLException ex) {
			throw new DataException(ex);
		} finally {            
			JDBCUtils.closeResultSet(resultSet);
			JDBCUtils.closeStatement(preparedStatement);
		}
	}
	
	private Resultado loadNext(ResultSet resultSet) throws Exception{


		Resultado r = new Resultado();
		int i = 1;
		Long id = resultSet.getLong(i++);
		String nome = resultSet.getString(i++);
		Long idtr = resultSet.getLong(i++);
		
		r.setIdResultado(id);
		r.setNombre(nome);
		r.setIdTipoResulatado(idtr);

		return r;

	}

}
